### ISSUE TITLE
Lista diaria e intradiaria

### ISSUE THREAD

**Issue by yael-lorenzo** [matbarofex/pyRofex#1]
Hola, estoy curioso respecto a la API **diaria** e **intradiaria** que no esta cubierta en este caso. 
Y otra cosa que no me cierra en los valores que veo es con el metodo
```get_trade_history```
que supuse al armalrlo tipo OHLC me daría  lo mismo que una **diaria vieja**.

Algun hint al respecto? 
Se los agradezco por adelantado!

**Comment by fzanuso** [comment]
Hola Yael!

Para consultar Market Data, tenés 2 métodos:
* get_market_data: para market data real-time, te devuelve el último valor para los entries de market data que le indiques 
* get_trade_history: para market data historica, te devuelve la lista de todos los Trades generados en el lapso de tiempo que le indicas

Respecto a los datos OHLC, si utilizas los datos de los trades historicos y calculas el OHLC tendría que darte de lo mismo, si no es así, te pido si me podes pasar un caso puntual para analizarlo y ver cual es el problema.

Consulta, respecto a la API que no está cubierta, a cual te referis especificamente?

**Comment by yael-lorenzo** [comment]
Hola!! 
Usando la siguiente imagen como referencia podemos ver que con el ticker **RFX20Sep19** para el **27-09-2019**, el volumen operado es **6** y 
```
Open		High		Low		Close
38352		38352		38186		38186
```

![image](https://user-images.githubusercontent.com/22622247/66076284-d9b32580-e533-11e9-99e0-0fea8d390987.png)

Cuando uso la API con get_trade_history, para la fecha e indicador establecido me devuelve 1734 registros y un volumen de 6172.
Adjunto json con la respueta. Ya esta mal el volumen, si armo el OHLC es cualquier cosa.
[rfx20sep19-2019-09-30.json.zip](https://github.com/matbarofex/pyRofex/files/3683075/rfx20sep19-2019-09-30.json.zip)

Res;pecto a las otras APIS, las de api/v1/platform/series/daily?sid=RFX20Sep19 y /api/v1/platform/series/intraday?sid=RFX20Sep19&from=2019-09-25T23%3A03%3A04.000Z&to=2019-09-30T23%3A04%3A04.000Z

**Comment by fzanuso** [comment]
Hola Yael, estuve analizando el caso y la info correcta es la que aparece en la API, matriz algunos días esta mostrando información diferente aunque no estoy seguro porque, ya comente el caso a rofex para que lo analizen. 

Si te fijas en el [CEM (Centro de Estadisticas del Mercado)](https://www.rofex.com.ar/cem/FyO.aspx), la info para ese día en particular es casí igual a la que devuelve la API (la diferencia minima viene porque el CEM tiene en cuenta las operaciones de pases RFXP 09/12 19) pero si los sumas el volumen es exactamente el mismo.

Por el tema de las APIs, estoy viendo con la gente de primary si las agregamos o no a la libreria.

**Comment by yael-lorenzo** [comment]
Gracias!
