### ISSUE TITLE
Market Data Historico

### ISSUE THREAD

**Issue by fedeturi** [matbarofex/pyRofex#10]
Hola.

Queria consultar lo siguiente dado que no encontré nada en la [documentación oficial de la API](https://apihub.primary.com.ar/assets/docs/Primary-API.pdf):
De ser posible, cómo puedo suscribirme a la MarketData histórica de un instrumento? 
Por ejemplo ver todos los `MarketDataEntry.HIGH_PRICE` históricos del ticker DODic20.

Gracias!

**Comment by fzanuso** [comment]
Hola, 

La Market Data Histórica solo se puede consultar mediante la API REST, y solo te devuelve los trades históricos (precio/cantidad/fecha). La API Websocket te permite suscribirte para recibir actualizaciones de Market Data pero son precios en tiempo real, no hay forma de pedir un histórico. La única alternativa que se me ocurre es que vos vayas almacenando los mensajes de MarketData que recibas e ir armando tu propio store de datos históricos.

Que yo sepa no se ha implementado otra consulta todavía. Igualmente para la respuesta oficial tendrías que consultar a mpi@primary.com.ar por cualquier novedad.

Saludos!
Franco

**Comment by fedeturi** [comment]
Hola @fzanuso , gracias por la respeusta.
Antes que nada permitime felicitarte por tu desarrollo.
Metiendo un poco de mano llegue a la misma conclusion que comentaste.

Me queda pendiente hacerte una pregunta que no me queda clara, mas conceptual.
Esto se podria lograr a traves de una sesion FIX? Enviando un mensaje acorde a las ROE?

No entiendo del todo la diferencia entre una sesion FIX, y conectarse a la API y enviar mensajes FIX por socket.

Muchas gracias!

**Comment by fzanuso** [comment]
Gracias Fede,

Mira para ponerlo en términos generales. Tanto las APIs FIX, Rest y Websocket te permiten hacer cosas muy similares. 

FIX es el estándar en la industria financiera, es decir, que casi todos los mercado del mundo ofrecen esta API (aunque es muy raro que la ofrezcan a retails). ROFEX ofrece esta API para conectarse aunque tiene la desventaja que no es tan sencilla de entender por lo que si no tenes experiencia con el estándar te va a llevar un tiempo el desarrollo. Por otro lado, ROFEX también ofrece APIs Rest/Websocket (las coloco juntas porque normalmente se utilizan así, aunque tranquilamente podes usar una u otra) que son mucho mas amigables para un desarrollador y permiten hacer desarrollos mas fácilmente y en menos tiempo. 

Por lo que la decisión de qué API utilizar para conectarte al Mercado va a depender mucho del objetivo que tengas. Si la idea es guardar precios históricos para luego hacer un análisis sobre los datos, o si querés ejecutar alguna estrategia de baja frecuencia que no dependa de la rapidez, tranquilamente podes usar la API Rest/Websocket. Por otro lado si tenes pensado hacer un sistema que se conecta a varios mercados y depende de la velocidad para ejecutar sus estrategias entonces FIX te va a ahorrar tiempo a futuro. 

En principio yo te recomiendo empezar con la API Rest/Websocket ya que tenes los conectores en varios lenguajes y podes hacer algo que funcione en poco tiempo. Después, si ves que te puede llegar a servir, podes hacer la conexión por FIX. 

Saludos!
Franco

**Comment by fedeturi** [comment]
Excelente @fzanuso , muchas gracias por la aclaracion!
