### ISSUE TITLE
Agregar book DEPTH para mensajes de MarketData por WebSocket 

### ISSUE THREAD

**Issue by fedeturi** [matbarofex/pyRofex#11]
Para potenciar las funcionalidades que brinda pyRofex, creo que resultaría muy util poder especificar la profundidad del order book que queremos recibir en cada mensaje de MarketData para los productos a los que estamos suscritos.

Considerando que actualmente sólo es posible hacer esto a traves de la API Rest usando el metodo `get_market_data()` y especificando el parámetro `depth` ; seíra una mejora considerable para implementar en bots de trading dada la limitación de cantidad de requests por segundo que impone la API Rest.

Por el momento la solución que encontre es la de enviar una request para pedir MarketData con la profundidad deseada cada vez que entra un mensaje por el socket, pero como menciono anteriormente, veo una limitación en la cantidad de requests por segundo, siendo que para algunos productos, la cantidad de actualizaciones por segundo es mayor a 1 por segundo.

Espero atento de existir una posibilidad de implementacióń en el corto plazo. Excelente desarrollo! Muchas gracias.

**Comment by fzanuso** [comment]
Hola Fede, muchas gracias por los comentarios!! Siempre es bueno el feedback, la verdad que se pueden mejorar varias cosas y la idea es ir haciéndolo a medida que se vayan necesitando.

Ya subí otra versión del código que permite agregar la profundidad en los msj de suscripción. Es la versión 0.3.1 que esta en el repositorio PyPI, por lo que haciendo un `pip install -U pyRofex`  deberías poder actualizar la versión localmente.

Lo probé y esta funcionando pero avisame cualquier cosa. 

Abz!

**Comment by fedeturi** [comment]
Hola Franco! 
Excelente, muchas gracias por atender el issue tan rapido. Lo voy a estar usando y cualquier cosa te mantengo al tanto.
Saludos!
