### ISSUE TITLE
Tipo de dato INT para price en vez de FLOAT

### ISSUE THREAD

**Issue by fedeturi** [matbarofex/pyRofex#13]
**Describe the bug**
Veo que en la definición del metodo `send_order()` de ` rest_rfx.py `, recibe un numero INT para el parámetro price, en vez de FLOAT. 
Esto es correcto? No impide colocar ordenes en el mercado con precios con valores decimales? 
Si bien lo vengo usando con numeros FLOAT, no habia prestado atencion y no recuerdo haber tenido problemas lanzando ordenes, pero pregunto por si hay algun error de comprension de mi parte.

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/13341103/100109255-6a407980-2e4a-11eb-891c-e24ee8a67d34.png)

Saludos!

**Comment by fzanuso** [comment]
Hola Fede! perdón la demora, estuve con otras cosas y no tenia mucho tiempo. Pero voy retomando con los pendientes.

Por este issue, tenes toda la razón, aunque es solo un typo en la documentación, como bien mencionas no te impide mandar un float.

Lo voy a corregir y subir junto con otro cambios.

Abrazo!

**Comment by fedeturi** [comment]
Hola Franco!

Excelente! 
Muchas gracias por las respuestas y por atender a las necesidades de los usuarios de la librerira.

Felicitaciones nuevamente!

**Comment by fzanuso** [comment]
Fix en la versión 0.3.2
