### ISSUE TITLE
Cierre de conexión websocket por falta de heartbeat

### ISSUE THREAD

**Issue by matiasrivera** [matbarofex/pyRofex#15]
Aparentemente es necesario enviar cada 30 segundos un mensaje vacío a través del websocket para que el servidor no cierre la conexión.

Entiendo que este debería ser un feature de la librería y no una preocupación del usuario final

**Comment by fzanuso** [comment]
Hola, por este tema, al establecer la conexión websocket se establece un hearbeat cada 270s que era suficiente para mantener la conexión activa, pero por lo que decis algo cambio. Voy a poner este valor en 30s por defecto pero que sea algo configurable por el usuario.

Gracias por el comentario!

**Comment by fzanuso** [comment]
Fix en la versión 0.3.2.

El heartbeat por defecto quedo en 30s, pero se puede actualizar con:

`pyRofex._set_environment_parameter("heartbeat", 120, pyRofex.Environment.REMARKET)`
