### ISSUE TITLE
Compatibilidad con Websocket-client v.0.58.0

### ISSUE THREAD

**Issue by nacho-herrera** [matbarofex/pyRofex#18]
La version 0.58.0 de websocket-client no es compatible. queda la conexión freezada sin recibir información. No tengo suficientes conocimientos para determinar qué es lo incompatible, pero no funciona. 
La version 0.57.0 si funciona.

**Comment by fedeturi** [comment]
@nacho-herrera para que puedas usarla mientras tanto, te recomiendo que crees un nuevo ambiente virtual de Python (o Conda) e instales la version 0.57.0 de WebSocket junto a pyRofex.

**Comment by nacho-herrera** [comment]
Gracias @fedeturi, hice eso. Supongo que modificando setup.py y poniendole que la version de websocket-client sea >=0.54.0 y <=0.57.0 deberia funcionar para nuevas instalaciones.

**Comment by DenisBochert** [comment]
Hola, soy nuevo en python, y cuando instalo me trae la version websocket-client 0.59.0 como puedo setear para que instale la 0.57.0? esoty usando python 3.9.4 , tengo que crearme un env con una vercion de python anterior?

**Comment by nacho-herrera** [comment]
> Hola, soy nuevo en python, y cuando instalo me trae la version websocket-client 0.59.0 como puedo setear para que instale la 0.57.0? esoty usando python 3.9.4 , tengo que crearme un env con una vercion de python anterior?

Hola Denis, lo que deberias hacer es lo siguiente, primero instala el paquete pyRofex, puede ser en un env o no, yo cree uno pero no es indispensable, luego en una pantalla de consola/cmd pones 
**pip uninstall websocket-client**
y por ultimo
**pip install websocket-client==0.57.0**

Si creaste un env primero tenes que activarlo (corriendo _env\scripts\activate_ siendo env el nombre del entorno)

Espero te funcione, cualquier cosa avisame.

**Comment by DenisBochert** [comment]
funciono, mil gracias!!!!
