### ISSUE TITLE
Invalid WebSocket Header on init_websocket_connection

### ISSUE THREAD

**Issue by twissell-** [matbarofex/pyRofex#22]
**Describe the bug**
Hola! Llevamos trabajando con pyrofex desde hace unos meses y esta semana nos topamos con este error. No estoy seguro de si cambio algo en la API, pero el mismo codigo que funcionaba la semana pasada, esta semana dejo de funcionar. Usamos pyRofex `0.4.1`, pero tambien nos pasa con la `0.4.2rc1`

Leimos los issues relacionado a wesocket y no parece ser un error ni del SSL cert ni de la version de websocket (estamos usando `0.57.0`).

**To Reproduce**
El error se puede reproducior con el siguiente snippet:

```py
import pyRofex

pyRofex.initialize(user="...",
                   password="...",
                   account="...",
                   environment=pyRofex.Environment.REMARKET)

def _marketDataHandler(message):
    print('MDH>', message)

def _errorHandler(message):
    print("Error: {0}".format(message))
    
def _exceptionHandler(e):
    print("Exception: {0}".format(e))

pyRofex.init_websocket_connection(
    market_data_handler=_marketDataHandler,
    error_handler=_errorHandler,
    exception_handler=_exceptionHandler)

```

Y genera la siguiente salida:

```
Exception: Invalid WebSocket Header
Exception: Connection could not be established.
```

**Additional context**
Le pusimos un print a websocket, a ver que estaba poniendo en el header y lo unico que hay es:

```
{'X-Auth-Token:qukUy...2lqqg4='}
```

Intentamos rastrear como se genera ese token, pero no lo pudimos encontrar.

Nos darias una mano para fixear esto? O al menos determinar si es problema de la API, de PyRofex o nuestro?

Gracias desde ya,

**Comment by vettocastillo** [comment]
Hola, yo estoy teniendo el mismo problema,
Saludos

**Comment by fplanas27** [comment]
Yo tambien etoy teniendo el mismo problema:

pyRofex.init_websocket_connection(order_report_handler=order_report_handler,
                                  error_handler=error_handler,
                                  exception_handler=exception_handler)
Exception Occurred: Invalid WebSocket Header
Exception Occurred: Connection could not be established.

**Comment by twissell-** [comment]
@juliansodo 

Ayer estuvimos probandolo y ahora funciona. El mismo codigo, sin ningun cambio. 

Alguna idea de que paso o que genero el error?

**Comment by juliansodo** [comment]
Buenas tardes!
Estuvimos revisando el problema y al parecer se trató de un inconveniente en el ambiente de pruebas de reMarkets. No hubieron cambios en la API ni antes, ni después de los reportes recibidos.
Luego del reinicio diario del ambiente, volvió a funcionar sin inconvenientes.

Cierro el Issue, cualquier cosa en que podamos ayudar, nos pueden contactar sobre el correo mpi@primary.com.ar y cualquier problema con la librería, pueden abrir un nuevo Issue siempre que necesiten.
Gracias por reportarlo.
Saludos.

**Comment by fplanas27** [comment]
Julian,
   perfecto, ahí funciona. ¡Genial!

Muchas gracias.

Federico Planas
***@***.***
