### ISSUE TITLE
Send and cancel orders via websocket

### ISSUE THREAD

**Issue by twissell-** [matbarofex/pyRofex#23]
Buenas!

Venimos trabajando hace varios meses en un bot usando `pyRofex` y estamos por arrancar el proceso de homologacion. En una de las reuniones previas que tuvimos con uno de los desarrolladores de Primary, nos hizo llegar una [lista de buenas practicas](https://apihub.primary.com.ar/assets/docs/Buenas%20practicas%20TRD.pdf) que debemos cumplir para poder homologar.

Ahi dice que la creacion y cancelacion de ordenes tiene que hacerse a travez del web socket pero no encontramos en `pyRofex` nada que nos permita hacerlo. Tampoco encontramos ejemplos buscando en internet.

Nuestra duda es: `pyRofex` tiene esa feature y no la estamos encontrando? O tenemos que mandar los mensajes a mano usando el websocket que crea `pyRofex`? Alguien tendra un ejemplo de como hacerlo?

Una cosa que nos intriga tambien es que no vimos que nadie haya levantado esto antes. Homologaron creando y cancelando las ordenes a travez de la API Rest? Capaz es un requerimiento que agregaron hace poco.

En cualquier caso, no estaria mal agregar estas features.

Gracias desde ya!

**Comment by UrielPaluch** [comment]
Buenas! les comento que realice por mi cuenta la implementación de estas funciones que requiere primary para homolgar las aplicaciones de trading. Abri un [pull request](https://github.com/matbarofex/pyRofex/pull/24) con la implementación y ya estoy en contacto con el owner de la librería para realizarlo correctamente. Mientras tanto pueden instalar la librería desde el [fork que hice](https://github.com/UrielPaluch/pyRofex/tree/issue/23).

Espero que les sirva, cualquier comentario sobre mi código es siempre bienvenido.

Saludos.

**Comment by twissell-** [comment]
Hola @UrielPaluch !

Yo hice lo mismo, tenia pensado pedir el MR, pero al final no me dio el tiempo. Si queres, podes [revisar el codigo](https://github.com/twissell-/pyRofex) por si hay algo que te sirva, pero me parece que el tuyo implementa la misma o mas funcionalidad.

Gracias!

**Comment by fzanuso** [comment]
@twissell-  @UrielPaluch Ya esta disponible la version 0.5.0rc1 con los cambios para envio de ordenes por WebSocket. Para instalarla hay que hacer:

`pip install pyRofex==0.5.0rc1`

Si la pueden probar seria un golazo. Si esta todo OK, ya dejo la version 0.5.0.

Saludos!

**Comment by UrielPaluch** [comment]
@fzanuso La estuve usando y no tuve ningún inconveniente.

Saludos!
