### ISSUE TITLE
Doesn't work ok behind proxy server

### ISSUE THREAD

**Issue by adriang1174** [matbarofex/pyRofex#3]
**Describe the bug**

**To Reproduce**

1. When working behind a proxy server (e.g. a company proxy) it throws an ApiException("Authentication fails. Incorrect User or Password")

2. The call to request.post (or get) doesn't include proxies param in args
3. The param "proxies" is included in request library but not used when called from rest_rfx.update_token and rest_rfx.api_request

**Expected behavior**
A param for include proxy server configuration should be included. The following should work ok:
proxies =  {'http': 'server.company.com:80'}

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: ALL

**Comment by fzanuso** [comment]
Hi Adrian, 

I created the branch _Issue-3/add_proxies_support_  with the fix. Could you confirm me if that fix the proxie problem? I added a new parameter to set the proxie when you initialize the environment, so it will use this param when sending the request as you suggest. 

Thanks!

**Comment by adriang1174** [comment]
I've tested it. It Works OK. I just added the param to pyRofex.initialize call and that's it.

pyRofex.initialize(user=user,
                   password=password,
                   account=account,
                   environment=pyRofex.Environment.REMARKET,
                   proxies=proxies)

Nice and elegant solution!
Thank you for your prompt response.

Are you going to close the issue? or merge the branch?

**Comment by fzanuso** [comment]
Excellent! Yes I merged it to master and close the issue.

Thanks for the feedback.
