### ISSUE TITLE
falla libreria pyRofex 

### ISSUE THREAD

**Issue by theisvo** [matbarofex/pyRofex#31]
Buenas estoy realizando pruebas de conexión con la librería pyRofex,  en Python versión 3.11.2 y me da el siguiente error:
import pyRofex
from datetime import datetime
import pandas as pd

market_data_recibida = []
reporte_de_ordenes = []

pyRofex.initialize(user = 'xxxxx', password = 'xxxxxx', account = 'xxxxxxx',
                   environment = pyRofex.Environment.REMARKET)

respuesta_listado_instrumento= pyRofex.get_detailed_instruments()

error:
from inspect import getargspec
ImportError: cannot import name 'getargspec' from 'inspect'

según lo que estuve investigando:
 El error que estás encontrando sugiere que la función getargspec no está disponible en el módulo inspect en la versión de Python que estás utilizando.
La función getargspec se depreció en Python 3 y se eliminó en Python 3.6. En su lugar, debes utilizar la función signature del módulo inspect para obtener información sobre los argumentos de una función.

hay posibilidad de actualizar la librería? o me sugieren alguna otra solución?
desde ya gracias, saludos

**Comment by fzanuso** [comment]
Hola, como decis es un tema de incompatibilidad con la version 3.11 de Python. Tengo que ver cual es la dependencia que esta teniendo problemas. 

Vi en un uno de los post que sugerian lo siguiente (aunque la verdad no lo probe):
https://stackoverflow.com/questions/74711405/importerror-cannot-import-name-getargspec-from-inspect-c-users-swapn-appd

> Run pip uninstall web3 to uninstall the old version, and run pip install git+https://github.com/ethereum/web3.py.git to install the new version off GitHub.
